version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: berkshire-backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env.prod
    environment:
      - ENV=prod
      - DATABASE_URL=postgresql://berkshire_user:secretpass@berkshire-db:5432/berkshire
      - REDIS_URL=redis://berkshire-redis:6379
    depends_on:
      - redis
      - db
    networks:
      - berkshire-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: berkshire-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://berkshire-backend:8000
    depends_on:
      - backend
    networks:
      - berkshire-net

  redis:
    image: redis:7-alpine
    container_name: berkshire-redis
    ports:
      - "6379:6379"
    networks:
      - berkshire-net

  db:
    image: postgres:15
    container_name: berkshire-db
    environment:
      POSTGRES_USER: berkshire_user
      POSTGRES_PASSWORD: secretpass
      POSTGRES_DB: berkshire
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - berkshire-net


networks:
  berkshire-net:
    driver: bridge

volumes:
  pg_data:
